import math
x = int (input("Enter The value of x: "))
print("  ")
y = int (input("Enter The value of y: "))
print("  ")
print("squerroot of 1st:", math.sqrt(x))
print("  ")
print("squerroot of 2nd:", math.sqrt(y))
print("  ")
print("Smallest intiger greater than or equal to x:", math.ceil(x))
print("  ")
print("copysign of x,y :", math.copysign(x,y))
print("  ")
print("absalute value of x  :", math.fabs(x))
print("  ")
print("checking x is not a number   :", math.isnan(x))